### ISSUE TITLE
assertUrl xml config error

### ISSUE THREAD

**Issue by cjdxhjj** [sebthom/oval#42]
when i upgrade to 2.1.2, it display an error flowing
'guardInterceptor' threw exception; nested exception is com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field net.sf.oval.constraint.AssertURLCheck.permittedURIScheme
---- Debugging information ----
message             : No such field net.sf.oval.constraint.AssertURLCheck.permittedURIScheme
field               : permittedURIScheme
class               : net.sf.oval.constraint.AssertURLCheck
required-type       : net.sf.oval.constraint.AssertURLCheck
converter-type      : net.sf.oval.configuration.xml.XMLConfigurer$1
path                : /oval/class/field[2]/assertURL/permittedURIScheme
class[1]            : net.sf.oval.configuration.pojo.elements.FieldConfiguration
required-type[1]    : net.sf.oval.configuration.pojo.elements.FieldConfiguration
class[2]            : net.sf.oval.configuration.pojo.elements.ClassConfiguration
required-type[2]    : net.sf.oval.configuration.pojo.elements.ClassConfiguration
class[3]            : net.sf.oval.configuration.pojo.POJOConfigurer
required-type[3]    : net.sf.oval.configuration.pojo.POJOConfigurer
version             : 1.4.11.1

i found the permittedURISchemes is List<URIScheme> in old release and 2.1.2 is Map<String, URIScheme> due to my prev report bug, the httpa schema test ok
but i don't understand why my config works, i wrote a AssertUrl and serialize to String, it format like <map><entry><key..></key><value>..</entry></map> or <list>..</list>
![image](https://user-images.githubusercontent.com/5616997/72656111-22ec8f80-39d4-11ea-9ee3-2b7fecb8ae3a.png)
so i debug into the code. i found
![image](https://user-images.githubusercontent.com/5616997/72656209-b58d2e80-39d4-11ea-93c8-265817346ab4.png)

**Comment by cjdxhjj** [comment]
it create a empty object and not init the property
![image](https://user-images.githubusercontent.com/5616997/72656256-ed947180-39d4-11ea-8748-4ff6863aa6da.png)
and then it lookup the generic type paramter annotaion with Constraint as a init config
![image](https://user-images.githubusercontent.com/5616997/72656307-4d8b1800-39d5-11ea-9855-9f76e438f1d6.png)
and set to the AssertUrlCheck

**Comment by cjdxhjj** [comment]
but set property is here, the property must not be null
![image](https://user-images.githubusercontent.com/5616997/72656346-a064cf80-39d5-11ea-98fe-b0a5cecb1e2d.png)
![image](https://user-images.githubusercontent.com/5616997/72656365-b83c5380-39d5-11ea-8c5b-73d46ae5b039.png)

**Comment by cjdxhjj** [comment]
it fail with a exception
![image](https://user-images.githubusercontent.com/5616997/72656384-d43ff500-39d5-11ea-8bc6-f6bd080f1e32.png)
that's why i must special the schema

**Comment by cjdxhjj** [comment]
finaly the property is also null
![image](https://user-images.githubusercontent.com/5616997/72656405-fdf91c00-39d5-11ea-91d5-e1be7911d629.png)

**Comment by cjdxhjj** [comment]
then it process another step to fill property value
![image](https://user-images.githubusercontent.com/5616997/72656457-457fa800-39d6-11ea-9eb8-4e2e65fa3080.png)

**Comment by cjdxhjj** [comment]
it lookup ImplicitCollectionMapping to set the collection property so i can set the collection property by flowing
![image](https://user-images.githubusercontent.com/5616997/72656509-9c857d00-39d6-11ea-9bac-eb41706368b4.png)

**Comment by cjdxhjj** [comment]
it can't find the ImplicitCollectionMapping  due to the type is not match, and then it become a unknow property and throw an error

**Comment by sebthom** [comment]
Thanks for reporting. Will be fixed in 2.1.3. Release is currently building.
